language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t faizshiraji/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true faizshiraji/react-test npm test

after_success:
  - docker build -t faizshiraji/multi-client ./client
  - docker build -t faizshiraji/multi-nginx ./nginx
  - docker build -t faizshiraji/multi-server ./server
  - docker build -t faizshiraji/multi-worker ./worker

# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
  - docker push faizshiraji/multi-client
  - docker push faizshiraji/multi-nginx
  - docker push faizshiraji/multi-server
  - docker push faizshiraji/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-978614123392
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY