sudo: required
services:
  - docker

before_install:
  - docker build -t faizshiraji/react-test ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true faizshiraji/react-test npm test -- --coverage

after_success:
  - docker build -t faizshiraji/multi-client ./client
  - docker build -t faizshiraji/multi-nginx ./nginx
  - dokcer build -t faizshiraji/multi-server ./server
  - docker build -t faizshiraji/multi-server ./worker
